CREATE TABLE IF NOT EXISTS mission (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  tx VARCHAR(80) UNIQUE,
  block INT,
  mission_id VARCHAR(20),
  reward DECIMAL(27,0),
  context VARCHAR(1000) COMMENT 'data',
  publisher VARCHAR(43),
  solution_num INT DEFAULT 0,
  filter TINYINT(1) DEFAULT 0,
  solved TINYINT(1) DEFAULT 0,
  txtime VARCHAR(40),
  updatetime DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- ALTER TABLE mission
-- ADD COLUMN filter TINYINT(1) DEFAULT 0 AFTER solution_num;
-- ALTER TABLE mission
-- MODIFY COLUMN context VARCHAR(1000);

CREATE TABLE IF NOT EXISTS solution (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  tx VARCHAR(80) UNIQUE,
  block INT,
  solution_id VARCHAR(20),
  mission_id VARCHAR(20),
  context VARCHAR(1000) COMMENT 'data',
  solver VARCHAR(43),
  status int DEFAULT 0,
  filter TINYINT(1) DEFAULT 0,
  txtime VARCHAR(40),
  updatetime DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- ALTER TABLE solution
-- ADD COLUMN filter TINYINT(1) DEFAULT 0 AFTER status;
-- ALTER TABLE solution
-- MODIFY COLUMN context VARCHAR(1000);

CREATE TABLE IF NOT EXISTS accept (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  tx VARCHAR(80) UNIQUE,
  block INT,
  solution_id VARCHAR(20),
  txtime VARCHAR(40),
  updatetime DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS reject (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  tx VARCHAR(80) UNIQUE,
  block INT,
  solution_id VARCHAR(20),
  txtime VARCHAR(40),
  updatetime DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS confirm (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  solution_id VARCHAR(20),
  arbitration_id VARCHAR(20),
  block INT,
  tx VARCHAR(80),
  txtime VARCHAR(40),
  updatetime DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS config (
  k VARCHAR(20) NOT NULL PRIMARY KEY,
  v VARCHAR(20),
  updatetime DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;